[[news]]
date = "2025-09"
content = "Two papers have been accepted by NeurIPS 2025! Three abstracts have been selected as RSNA 2025 Oral!"

[[news]]
date = "2025-06"
content = "Two papers have been accepted by MICCAI 2025!"

[[news]]
date = "2025-01"
content = "Two papers have been accepted by ISBI 2025. One paper has been accepted by ESWA."

[[news]]
date = "2024-06"
content = "One paper has been accepted by MICCAI 2024!"

